config/routes.rb
Rails.application.routes.draw do
  get 'business_qr_codes/show'
  namespace :admin do
    resources :administrators
    resources :customers
    resources :owners
    resources :businesses
    resources :business_follows
    resources :menus
    resources :categories
    resources :items
    resources :tags
    resources :item_tags
    resources :happy_prices
    resources :happy_codes

    root to: 'administrators#index'
  end

  # No sign up for admin
  get '/administrators/sign_up', to: 'static_pages#you_tried'
  devise_for :administrators
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks' }
  devise_for :owners
  devise_scope :customer do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # For Owners, some REST actions exept show are handle by devise :
  resources :owners, only: [:show]
  resources :customers, only: [:show]
  resources :business_follows, only: %i[create destroy]
  resources :happy_prices, only: [:index]

  resources :businesses do
    resources :menus, only: %i[show new create edit update destroy] do
      resources :menu_items, only: %i[create destroy]
    end
    resources :items do
      resources :happy_prices, only: %i[new create edit update destroy] do
        resources :happy_codes, only: %i[create]
      end
      resources :item_photos, only: [:create]
      resources :item_tags, only: %i[create destroy]
    end
    resources :business_photos, only: [:create]
    resources :business_qr_codes, only: [:index]
  end

  # Root is index of all businesses
  root 'businesses#index'

  get '/kit_ui', to: 'static_pages#kit_ui'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/businesses_controller.rb
# frozen_string_literal: true

module Admin
  class BusinessesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :authenticate_owner!, only: %i[new create destroy edit update]

  def index
    @businesses = Business.all
    @is_from_root = true
  end

  def show
    @business = Business.find(params[:id])
    @happy_prices = HappyPrice.all.where(item_id: Item.all.where(business_id: @business.id))
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.owner = current_owner

    if @business.save
      flash[:success] = 'Votre établissement a été créé avec succès !'
      redirect_to owner_path(current_owner)
    else
      render new_business_path
    end
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to business_path(@business.id)
    else
      flash[:warning] = "Nous n'avons pas pu modifier votre établissement"
      redirect_to edit_business_path(@business.id)
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to owner_path(current_owner)
  end

  private

  def business_params
    params.require(:business).permit(:name, :address, :phone)
  end
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true

module BusinessesHelper
end

app/views/businesses/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br>

      <% if @business.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>La modification n'a pu aboutir pour les raisons suivantes :</p>
        </div>
        <div class="alert alert-warning" role="alert">
          <ul>
            <% @business.errors.full_messages.each do |message| %>
              <li> <%= message %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h1 class="h3 mb-3 font-weight-normal text-center ">Modifier les informations de l'établissement</h1>

      <%= form_for @business do |ƒ| %>

        <div class="form-group">
          <label> Nom de l'établissement </label>
          <%= ƒ.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <label> Numéro de téléphone </label>
          <%= ƒ.text_field :phone, class: 'form-control' %>
        </div>

        <div class="form-group">
          <label> Adresse </label>
          <%= ƒ.text_field :address, class: 'form-control' %>
        </div>

        <%if @business.business_photo.attached?%>
          <%= image_tag @business.business_photo, alt: 'photo' %>
        <%else%>
          <p>=== Aucune photo n'est rattachée à cet établissement ===</p>
        <%end%>

        <div class="actions mt-5">
          <%= submit_tag 'Enregistrer les modifications', class: "btn btn-lg btn-success btn-block"%>
        </div>

      <%end%>

      <br>
      <%= link_to "Supprimer l'établissement", business_path(@business.id), data: {confirm: "Etes-vous sûr ?"}, method: :delete, :class => "btn btn-danger btn-lg btn-block my-2 mb-4" %>

    </div>
  </div>
</div>

app/views/businesses/index.html.erb
<!-- Basic Card Section Section -->
<section id="blog" class="section">
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s">Les Meilleurs <span>parmis les meilleurs</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s">En tout cas, nous n'en doutons pas.</p>
    </div>
    <div class="row justify-content-center">
      <% @businesses.all.each do |business| %>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 blog-item">
          <!-- Blog Item Starts -->
          <%= link_to business_path(business.id) do %>
            <div class="blog-item-wrapper wow fadeInUp" data-wow-delay="0.3s">
              <div class="blog-item-img">
                <%if business.business_photo.attached?%>
                  <%= image_tag business.business_photo, alt: 'photo', :class => "root-card-image" %>
                <% else %>
                  <%= image_tag 'burger.png', :class => "root-card-image" %>
                <% end %>
              </div>
              <div class="blog-item-text">
                <h3>
                  <%= link_to business.name, business_path(business.id) %>
                </h3>
                <div class="meta-tags">
                  <span class="businesscategory"><i class="lnr lnr-store"></i>Restaurant au top</span>
                </div>
                <p>
                  <i class="lnr lnr-map-marker"> </i><%= business.address %><br>
                  <i class="lnr lnr-phone-handset"> </i><%= business.phone %>
                </p>
                <% if customer_signed_in? %>
                  <% if current_customer.businesses.include?(business) %>
                    <%= link_to "Ne plus suivre", business_follow_path(:id => business.id), method: :delete, :class => "btn btn-danger my-2" %>
                  <% else %>
                    <%= link_to "Suivre l'établissement", business_follows_path(:id => business.id), method: :post, :class => "btn btn-common my-2" %>
                  <% end %>
                <% end %>
              </div>
              <% if business.number_happy_prices != 0 %>
                <ul class="list-group list-group-flush bg-green">
                  <%= link_to "#{business.number_happy_prices} Happy Minutes en cours !", business_items_path(:business_id => business.id), :class => "btn btn-common my-2" %>
                </ul>
              <% end %>
            </div>
          <% end %>
          <!-- Blog Item Wrapper Ends-->
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/businesses/new.html.erb
<div class="container">
  <div class="section-header">
    <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Créez votre <span>établissement</span></h2>
    <hr class="lines wow zoomIn" data-wow-delay="0.3s">
    <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Renseignez les informations</p>
  </div>

  <div class="row">
    <div class="col-md-6 offset-md-3">

      <% if @business.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>La création de l'établissement n'a pu aboutir pour les raisons suivantes :</p>
        </div>
        <div class="alert alert-warning" role="alert">
          <ul>
            <% @business.errors.full_messages.each do |message| %>
              <li> <%= message %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model: @business, local: true do |form| %>

        <div class="form-group row">
          <div class="col-lg-3"> <%= form.label :name, "Nom de l'établissement" %> </div>
          <div class="col-lg-9">
            <%= form.text_field :name, class: "form-control"  %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-lg-3"> <%= form.label :address, "Adresse de l'établissement" %> </div>
          <div class="col-lg-9">
            <%= form.text_field :address, class: "form-control"  %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-lg-3"> <%= form.label :phone, "Numéro de téléphone" %> </div>
          <div class="col-lg-9">
            <%= form.text_field :phone, class: "form-control"  %>
          </div>
        </div>

        <div class="actions my-4 row justify-content-center">
          <%= form.submit "Valider", class: "btn btn-outline-success btn-block col-lg-9 mb-4", style: "margin: 10px 0;" %>
        </div>

        <div class="actions my-4 row justify-content-center">
          <%= link_to "Retour au Profil", owner_path(current_owner), class: "btn btn-common col-lg-9 mb-4", style: "margin: 10px 0;" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/businesses/show.html.erb
<div class="container mt-4 ">
  <div class="row justify-content-center">
    <div class="col-lg-7 col-md-7 d-flex align-items-center flex-column">
      <%if @business.business_photo.attached?%>
        <%= image_tag @business.business_photo, class: "business-show-image", alt: 'photo' %>
      <%end%>
      <% if current_owner == @business.owner %>
        <p class="h4">Changer de photo ?</p>
        <%= form_tag business_business_photos_path(@business), :class => "business-show-card-image pl-5 ml-5", multipart: true do %>
          <%= file_field_tag :business_photo %>
          <%= submit_tag "mettre à jour", class: "btn btn-outline-secondary btn-sm" %>
        <% end %>
      <% end %>
    </div>

    <div class="col-lg-5 col-md-7">
      <h2 class="font-weight-bold"><%= @business.name %></h2>
      <p><span class="lnr lnr-map-marker"></span> <%= @business.address %></p>
      <p><span class="lnr lnr-phone"></span> <%= link_to @business.phone, "tel:#{@business.phone}" %> </p>
      <p>
        <%= link_to "Voir la carte", business_items_path(@business), :class => "btn btn-common mt-2" %>
      </p>
      <% if current_owner == @business.owner %>
        <p>
          <%= link_to "Modifier les informations de votre établissement", edit_business_path, :class => "btn btn-common mb-2 mt-5" %>
        </p>
        <p>
          <%= link_to "Voir mon QR Code", business_business_qr_codes_path(@business), :class => "btn btn-common my-2" %>
        </p>
      <% end %>
      <% if customer_signed_in? %>
        <% if current_customer.businesses.include?(@business) %>
          <%= link_to "Ne plus suivre", business_follow_path(:id => @business.id), method: :delete, :class => "btn btn-danger my-2" %>
        <% else %>
          <%= link_to "Suivre l'établissement", business_follows_path(:id => @business.id), method: :post, :class => "btn btn-common my-2" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% if @business.number_happy_prices != 0 %>

  <!-- Basic Card Section Section -->
  <section id="blog" class="section d-flex align-items-center flex-column">
    <!-- Container Starts -->
    <div class="container">
      <div class="section-header">
        <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s">Nos Happy Minutes <span>du moment</span></h2>
        <hr class="lines wow zoomIn" data-wow-delay="0.3s">
        <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s">Profitez-en !</p>
      </div>

      <% @happy_prices.each do |happy_price| %>
        <% if happy_price.active? %>
          <div class="row justify-content-center">
            <% item = happy_price.item %>
            <!-- ( Item Wrapper -->
            <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 blog-item">

              <!-- ( Happy Minute Begin !-->
              <div class="alert alert-success wow fadeInUp" data-wow-delay="0.3s">
                <p class="display-4"> HAPPY MINUTE : <%= happy_price.price %> € </p>

                <span class="badge badge-pill badge-primary p-4 my-1 mx-1">Disponibles : <%= happy_price.stock %></span>
                <span class="badge badge-pill badge-primary p-4 my-3">Temps restant : <%= happy_price.time_str_french %></span>

                <!-- Happy Minute Begin ) !-->

                <div class="blog-item-wrapper wow fadeInUp" data-wow-delay="0.3s">
                  <div class="blog-item-text">
                    <div class="row">
                      <div class="col-4">
                        <h3>
                          <%= link_to item.title, business_item_path(@business, item) %>
                        </h3>
                        <div class="meta-tags">
                          <span class="foodcategory"><i class="lnr lnr-cloud"></i> <%= item.category.name %> </span><br>
                        </div>
                      </div>
                      <div class="col-6">
                        <p>
                          <%= item.description %>
                        </p>
                      </div>
                      <div class="col-2">
                        <p>
                          <% if happy_price %>
                            <del><%= item.price %> € </del>
                          <% end %>
                        </p>
                      </div>
                    </div>
                  </div>

                </div>
                <!-- ( Happy Minute End !-->
                <% if current_owner == @business.owner %>
                  <%= link_to "Modifier (#{happy_price.price} €)", edit_business_item_happy_price_path(@business, item, happy_price), class: "btn btn-common display-4"%>
                <% elsif customer_signed_in? %>
                  <%= link_to "Bénéficier de la promo incroyable !", business_item_happy_price_happy_codes_path(@business, item, happy_price), method: :post, class: "btn btn-primary" %>
                <% else %>
                  <%= link_to "Se connecter pour en profiter", new_customer_session_path, class: "btn btn-success" %>
                <% end %>

              </div>
              <!-- Happy Minute End ) -->
            </div>
          </div>
          <!-- Item Wrapper ) -->
        <% end %>
      <% end %>

    </div>
  </section>

<% else %>
  <section id="blog" class="section d-flex align-items-center flex-column">
    <div class="container">
      <div class="section-header">
        <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s">Nouveaux Happy Minutes</h2>
        <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      </div>
      <div class="row justify-content-center">
        <%= image_tag "coming_soon.jpg", width: 400 %>
      </div>
    </section>
  <% end %>