config/routes.rb
Rails.application.routes.draw do
  get 'business_qr_codes/show'
  namespace :admin do
    resources :administrators
    resources :customers
    resources :owners
    resources :businesses
    resources :business_follows
    resources :menus
    resources :categories
    resources :items
    resources :tags
    resources :item_tags
    resources :happy_prices
    resources :happy_codes

    root to: 'administrators#index'
  end

  # No sign up for admin
  get '/administrators/sign_up', to: 'static_pages#you_tried'
  devise_for :administrators
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks' }
  devise_for :owners
  devise_scope :customer do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # For Owners, some REST actions exept show are handle by devise :
  resources :owners, only: [:show]
  resources :customers, only: [:show]
  resources :business_follows, only: %i[create destroy]
  resources :happy_prices, only: [:index]

  resources :businesses do
    resources :menus, only: %i[show new create edit update destroy] do
      resources :menu_items, only: %i[create destroy]
    end
    resources :items do
      resources :happy_prices, only: %i[new create edit update destroy] do
        resources :happy_codes, only: %i[create]
      end
      resources :item_photos, only: [:create]
      resources :item_tags, only: %i[create destroy]
    end
    resources :business_photos, only: [:create]
    resources :business_qr_codes, only: [:index]
  end

  # Root is index of all businesses
  root 'businesses#index'

  get '/kit_ui', to: 'static_pages#kit_ui'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/happy_price.rb
class HappyPrice < ApplicationRecord
  belongs_to :item
  has_many :happy_codes

  validates :price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  validate :dates_dont_overlap
  validate :lower_price
  validate :start_date_after_now
  validate :start_date_before_end_date

  after_create :notify_followers_email

  def started?
    start_date && start_date <= DateTime.now
  end

  def ended?
    end_date && end_date < DateTime.now
  end

  def in_stock?
    stock > 0
  end

  def stock
    quantity ? quantity - happy_codes.size : 0
  end

  def time
    TimeDifference.between(DateTime.now, end_date || DateTime.now)
  end

  def time_str_french
    time.humanize
        .gsub('and', 'et')
        .gsub('Seconds', 'secondes')
        .gsub('Second', 'seconde')
        .gsub('Hours', 'heures')
        .gsub('Hour', 'heure')
        .gsub('Days', 'jours')
        .gsub('Day', 'jour')
  end

  def active?
    started? && !ended? && in_stock? && !id.nil?
  end

  # FIXME: what happens if 2 customers click exact same time for last happy_price in stock?
  def get_new_code
    code = rand(1000..9999)
    if !active?
      nil
    elsif happy_codes.any? { |hc| hc.code == code }
      get_new_code
    else
      code
    end
  end

  private

  def notify_followers_email
    # Deliver the mail to notify the followers
    # ----------------------------------------
    # See https://stackoverflow.com/questions/8709984/how-to-catch-error-exception-in-actionmailer

    CustomerMailer.with(happy_price: self).notify_followers_email.deliver_now
  rescue Exception => e
  end

  def start_date_before_end_date
    return unless start_date && end_date

    errors.add(:end_date, 'La date de fin doit être après la date de début') unless start_date < end_date
  end

  def start_date_after_now
    return unless start_date

    errors.add(:end_date, 'La date de fin doit être dans le futur') unless DateTime.now < end_date
  end

  def dates_dont_overlap
    return unless price && start_date && end_date

    overlapping = item.happy_prices.filter do |happy_price|
      start_date < happy_price.end_date && happy_price.start_date < end_date && happy_price != self
    end.first
    errors.add(:start_date, "Le Happy Minute chevauche un autre à #{overlapping.price} €") unless overlapping.nil?
  end

  def lower_price
    return unless price

    errors.add(:price, "Le prix doit être inférieur au prix usuel de #{item.price} €") unless price < item.price
  end
end

app/controllers/admin/happy_prices_controller.rb
# frozen_string_literal: true

module Admin
  class HappyPricesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/happy_prices_controller.rb
class HappyPricesController < ApplicationController
  before_action :authenticate_owner!, except: [:index]

  def index
    @business
    @happy_prices = HappyPrice.all
  end

  def new
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:item_id])
    @happy_price = @item.happy_prices.new
  end

  def create
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:item_id])
    @happy_price = @item.happy_prices.new(happy_price_params)
    if @happy_price.save
      redirect_to business_item_path(@business, @item), flash: { success: 'Happy Minute créé' }
    else
      render :new
    end
  end

  def edit
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:item_id])
    @happy_price = @item.happy_prices.find(params[:id])
  end

  def update
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:item_id])
    @happy_price = @item.happy_prices.find(params[:id])
    if @happy_price.update(happy_price_params)
      redirect_to business_item_path(@business, @item), flash: { success: 'Happy Minute mis à jour' }
    else
      render :edit
    end
  end

  def destroy
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:item_id])
    @happy_price = @item.happy_prices.find(params[:id])
    @happy_price.destroy
    redirect_to business_item_path(@business, @item), flash: { success: 'Happy Minute supprimé' }
  end

  private

  def happy_price_params
    params.require(:happy_price).permit(:price, :quantity, :start_date, :end_date)
  end
end

app/helpers/happy_prices_helper.rb
module HappyPricesHelper
end

app/views/happy_prices/_form.html.erb
  <%= form_with(model: [@business, @item, @happy_price], local: true, method: method, class: "col-lg-6") do |form| %>

  <!-- ERRORS !-->
  <% if @happy_price.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <p> Le produit n'a pas pu être créé pour les raisons suivantes :</p>
      <ul>
        <% @happy_price.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- price !-->
  <div class="form-group">
    <%= form.label :price, 'Prix' %>
    <%= form.number_field :price, step: 0.01, min: 0.01, class: "form-control text-primary"  %>
  </div>

  <!-- quantity !-->
  <div class="form-group">
    <%= form.label :quantity, 'Quantité' %>
    <%= form.number_field :quantity, step: 1, min:1 , class: "form-control text-primary"  %>
  </div>

  <!-- start and end dates !-->
  <div class="form-group">
    <%= form.datetime_select  :start_date, class: "form-control"  %>
    <%= form.label :start_date, 'Début' %>
  </div>
  <div class="form-group">
    <%= form.datetime_select  :end_date, class: "form-control"  %>
    <%= form.label :end_date, 'Fin' %>
  </div>

  <!-- SUBMIT !-->
  <div class="actions mt-5">
    <%= form.submit "Valider", class: "btn btn-lg btn-primary btn-block" %>
  </div>

  <div class="row justify-content-center">
    <%= link_to "Retour au produit", business_item_path(@business, @item), class: "btn btn-info" %>
  </div>

<% end %>

app/views/happy_prices/edit.html.erb
<%= render partial: "items/header" %>

<section id="blog" class="section">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Modifier un <span>Happy Minute</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Merci de renseigner les informations suivantes </p>
    </div>
    <div class="row justify-content-center">
      <%= render partial: "items/item", locals:{item: @item, hide_happy_price: true} %>
    </div>

    <% upcoming = @happy_price %>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-6 col-sm-6 col-xs-12  alert alert-<%= (upcoming.active? ? ('success') : ('warning')) %>" >
        <h2> En cours de modification : </h2>
        <p> <%= upcoming.start_date.to_formatted_s(:long) %> ==> <%= upcoming.end_date.to_formatted_s(:long) %> </p>
        <p> <%= upcoming.stock %> unités à <%= upcoming.price %> € (<%= upcoming.active? ? 'EN COURS' : (upcoming.started? ? 'Terminé' : 'à venir') %>)</p>
      </div>
    </div>

    <div class="row justify-content-center">
      <%= render partial: "form", locals: {method: :put} %>
    </div>

  </div>

  <div class="container">
    <div class="section-header">
      <%= link_to "Supprimer", business_item_happy_price_path(@business, @item, @happy_price), method: :delete, data: {confirm: "Etes-vous sûr ?"}, class: "btn btn-danger" %>
    </div>
  </div>

</section>

app/views/happy_prices/index.html.erb
<!-- Basic Card Section Section -->
<section id="blog" class="section d-flex align-items-center flex-column">

  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s">Nos <span>Happy Minutes</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s">faites votre choix</p>
    </div>

    <div class="row justify-content-center">
      <% @happy_prices.each do |happy_price| %>
        <% if happy_price.active? %>
          <% item = happy_price.item %>
          <% business = item.business %>

          <!-- ( Item Wrapper -->
          <div class="col-lg-12 col-md-10 col-sm-12 col-xs-12 blog-item">

            <!-- ( Happy Minute Begin !-->
            <div class="alert alert-success wow fadeInUp" data-wow-delay="0.3s">
              <p class="display-4"> HAPPY MINUTE : <%= happy_price.price %> € </p>

              <span class="badge badge-pill badge-primary p-4 my-1 mx-1">Disponibles : <%= happy_price.stock %></span>
              <span class="badge badge-pill badge-primary p-4 my-1">Temps restant : <%= happy_price.time_str_french %></span>
              <span class="btn btn-outline-warning p-4 mb-4 ml-4"><%= link_to "Restaurant : #{business.name}", business_path(business.id) %></span>
              <!-- Happy Minute Begin ) !-->

              <div class="blog-item-wrapper wow fadeInUp" data-wow-delay="0.3s">
                <div class="blog-item-text">
                  <div class="row">

                    <div class="col-4">
                      <% if current_owner == item.business.owner %>
                        <h3>
                          <%= link_to item.title, business_item_path(business, item) %>
                        </h3>
                      <% else %>
                        <h3>
                          <%= item.title %>
                        </h3>
                      <% end %>
                      <div class="meta-tags">
                        <span class="foodcategory"><i class="lnr lnr-cloud"></i> <%= item.category.name %> </span><br>
                      </div>
                    </div>
                    <div class="col-6">
                      <p><%= item.description %></p>
                    </div>
                    <div class="col-2">
                      <p><del><%= item.price %> € </del></p>
                    </div>

                  </div>
                </div>
              </div>

              <% if current_owner == business.owner %>
                <%= link_to "Modifier (#{happy_price.price} €)", edit_business_item_happy_price_path(business, item, happy_price), class: "btn btn-common display-4"%>
              <% elsif customer_signed_in? %>
                <%= link_to "Bénéficier de la promo incroyable !", business_item_happy_price_happy_codes_path(business, item, happy_price), method: :post, class: "btn btn-primary" %>
              <% else %>
                <%= link_to "Se connecter pour en profiter", new_customer_session_path, class: "btn btn-success" %>
              <% end %>

            </div>
            <!-- Happy Minute End ) -->

          </div>
          <!-- Item Wrapper ) -->
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- End container ) -->
</section>

app/views/happy_prices/new.html.erb
<%= render partial: "items/header" %>

<section id="blog" class="section">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Ajouter un <span>Happy Minute</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Merci de renseigner les informations suivantes </p>
    </div>
    <div class="row justify-content-center">
      <%= render partial: "items/item", locals:{item: @item} %>
    </div>

    <div class="row justify-content-center">
      <%= render partial: "form", locals: {method: :post} %>
    </div>
  </div>
</section>