config/routes.rb
Rails.application.routes.draw do
  get 'business_qr_codes/show'
  namespace :admin do
    resources :administrators
    resources :customers
    resources :owners
    resources :businesses
    resources :business_follows
    resources :menus
    resources :categories
    resources :items
    resources :tags
    resources :item_tags
    resources :happy_prices
    resources :happy_codes

    root to: 'administrators#index'
  end

  # No sign up for admin
  get '/administrators/sign_up', to: 'static_pages#you_tried'
  devise_for :administrators
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks' }
  devise_for :owners
  devise_scope :customer do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # For Owners, some REST actions exept show are handle by devise :
  resources :owners, only: [:show]
  resources :customers, only: [:show]
  resources :business_follows, only: %i[create destroy]
  resources :happy_prices, only: [:index]

  resources :businesses do
    resources :menus, only: %i[show new create edit update destroy] do
      resources :menu_items, only: %i[create destroy]
    end
    resources :items do
      resources :happy_prices, only: %i[new create edit update destroy] do
        resources :happy_codes, only: %i[create]
      end
      resources :item_photos, only: [:create]
      resources :item_tags, only: %i[create destroy]
    end
    resources :business_photos, only: [:create]
    resources :business_qr_codes, only: [:index]
  end

  # Root is index of all businesses
  root 'businesses#index'

  get '/kit_ui', to: 'static_pages#kit_ui'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<div class="container">
  <% flash.each do |key, value|
  type = 'secondary'
  type = 'success' if %i[success].include?(key.to_sym)
  type = 'primary' if %i[notice info].include?(key.to_sym)
  type = 'danger' if %i[error].include?(key.to_sym)
  type = 'warning' if %i[alert warning].include?(key.to_sym)
  %>
  <div class="alert alert-<%= type %> alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value %>
  </div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<!-- Footer Section Start -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="social-icons wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s">
          <ul>
            <li class="facebook"><%= link_to("https://www.facebook.com/thehackingproject/") do %><i class="fa fa-facebook"></i><% end %></li>
            <li class="twitter"><%= link_to("https://twitter.com/the_hacking_pro?lang=fr") do %><i class="fa fa-twitter"></i><% end %></li>
            <li class="linkedin"><%= link_to("https://www.linkedin.com/school/the_hacking_project/") do %><i class="fa fa-linkedin"></i><% end %></li>
          </ul>
        </div>
        <div class="site-info wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="0.3s">
          <p> <a href="https://github.com/the-hacking-team/happy-minute"> Happy Minute GitHub </a> project by The Hacking Team </p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

app/views/shared/_navbar.html.erb
<div class="menu-wrap">
  <nav class="menu navbar">
    <div class="icon-list navbar-collapse">
      <ul class="navbar-nav">

        <% if customer_signed_in? %>
          <li class="nav-item">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Happy Minute", happy_prices_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mon profil", customer_path(current_customer), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Déconnexion", destroy_customer_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>

        <% if owner_signed_in? %>
          <li class="nav-item">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mon profil", owner_path(current_owner), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Déconnexion", destroy_owner_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>

        <% if administrator_signed_in? %>
          <li class="nav-item">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Déconnexion administrateur", destroy_administrator_session_path, method: :delete, class: "nav-link" %>
          </li>
        <%end%>

        <% if !administrator_signed_in? && !owner_signed_in? && !customer_signed_in? %>
          <li>
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Professionnel
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Se connecter", new_owner_session_path, class: "nav-link" %>
              <%= link_to "S'inscrire", new_owner_registration_path, class: "nav-link" %>
            </div>
          </li>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Consommateur
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Se connecter", new_customer_session_path, class: "nav-link" %>
              <%= link_to "S'inscrire", new_customer_registration_path, class: "nav-link" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <button class="close-button" id="close-button"><i class="lnr lnr-cross"></i></button>
</div>

<!-- Header Section Start -->

<header id="video-area" data-stellar-background-ratio="0.5">
  <div class="jumbotron jumbotron-fluid text-white my-jumbotron">
    <div id="block"></div>
    <div class="fixed-top">
      <div class="container">
        <div class="logo-menu">
          <%= link_to root_path, class: 'logo' do %>
            <span class="lnr lnr-dinner"></span><%= image_tag 'burger.png', style: 'height:45px;width:45px;margin-bottom:20px;' %> Happy Minute</a>
          <button class="menu-button" id="open-button"><i class="lnr lnr-menu"></i></button>
        <% end %>
      </div>
    </div>
  </div>

  <div class="overlay overlay-2"></div>
  <% if @is_from_root %>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-md-10">
          <div class="contents text-center">
            <h1 class="wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s">Des promotions éphèmères dans les meilleurs bars et restaurants</h1>
            <p class="lead wow fadeIn" data-wow-duration="1000ms" data-wow-delay="400ms">Nos Happy Minutes exclusives accessibles en Un Clic !</p>
            <% if customer_signed_in? %>
              <%= link_to "Nos Happy Minutes", happy_prices_path, class: "btn btn-common wow fadeInUp", data: { "wow-duration" => "1000ms", "wow-delay" => "400ms" } %>
            <% elsif owner_signed_in? %>
              <%= link_to "Mon profil", owner_path(current_owner), class: "btn btn-common wow fadeInUp", data: { "wow-duration" => "1000ms", "wow-delay" => "400ms" } %>
            <% else %>
              <%= link_to "Nos Happy Minutes", happy_prices_path, class: "btn btn-common wow fadeInUp", data: { "wow-duration" => "1000ms", "wow-delay" => "400ms" } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
</header>

<!-- Header Section End -->