config/routes.rb
Rails.application.routes.draw do
  get 'business_qr_codes/show'
  namespace :admin do
    resources :administrators
    resources :customers
    resources :owners
    resources :businesses
    resources :business_follows
    resources :menus
    resources :categories
    resources :items
    resources :tags
    resources :item_tags
    resources :happy_prices
    resources :happy_codes

    root to: 'administrators#index'
  end

  # No sign up for admin
  get '/administrators/sign_up', to: 'static_pages#you_tried'
  devise_for :administrators
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks' }
  devise_for :owners
  devise_scope :customer do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # For Owners, some REST actions exept show are handle by devise :
  resources :owners, only: [:show]
  resources :customers, only: [:show]
  resources :business_follows, only: %i[create destroy]
  resources :happy_prices, only: [:index]

  resources :businesses do
    resources :menus, only: %i[show new create edit update destroy] do
      resources :menu_items, only: %i[create destroy]
    end
    resources :items do
      resources :happy_prices, only: %i[new create edit update destroy] do
        resources :happy_codes, only: %i[create]
      end
      resources :item_photos, only: [:create]
      resources :item_tags, only: %i[create destroy]
    end
    resources :business_photos, only: [:create]
    resources :business_qr_codes, only: [:index]
  end

  # Root is index of all businesses
  root 'businesses#index'

  get '/kit_ui', to: 'static_pages#kit_ui'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :business
  has_many :happy_prices
  has_one_attached :item_photo
  has_many :item_tags, dependent: :delete_all
  has_many :tags, through: :item_tags
  belongs_to :category

  validates :title, presence: true
  validates :price, presence: true
  validates :category_id, presence: true
  validates :description, presence: true

  def current_happy_price
    happy_prices.filter(&:active?).first
  end

  def upcoming_happy_prices
    happy_prices.filter { |hp| !hp.started? }
  end
end

app/controllers/admin/items_controller.rb
# frozen_string_literal: true

module Admin
  class ItemsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_owner!, only: %i[new create edit update destroy]

  def index
    @business = Business.find(params[:business_id])
    @categories = Category.all
    @items = @business.items
  end

  def show
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:id])
  end

  def new
    @business = Business.find(params[:business_id])
    @item = @business.items.new
  end

  def create
    @business = Business.find(params[:business_id])
    @item = @business.items.new(item_params)
    @item.available = true

    if @item.save
      redirect_to business_item_path(@business, @item), flash: { success: 'Produit créé' }
    else
      render :new
    end
  end

  def edit
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:id])
    @item_tag = @item.item_tags.new
  end

  def update
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:id])
    if @item.update(item_params)
      redirect_to business_item_path(@business, @item), flash: { success: 'Produit mis à jour' }
    else
      @item_tag = @item.item_tags.new
      render :edit
    end
  end

  def destroy
    @business = Business.find(params[:business_id])
    @item = @business.items.find(params[:id])
    @item.destroy
    redirect_to business_items_path(@business), flash: { success: 'Produit supprimé' }
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :category_id, :price, :available)
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_category.html.erb
<% if @items.find_by(category_id: category.id) %>
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 blog-item">
      <h1>
        <%= category.name %>
      </h1>
    </div>
  </div>

  <% @items.each do |item| %>
    <% if item.category_id == category.id %>
      <div class="row justify-content-center">

        <% happy_price = item.current_happy_price %>
        <!-- ( Item Wrapper -->
        <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 blog-item">
          <% if happy_price %>
            <!-- ( Happy Minute Begin !-->
            <div class="alert alert-success wow fadeInUp" data-wow-delay="0.3s">
              <p class="display-4"> HAPPY MINUTE :
                <%= happy_price.price %> € </p>
              <span class="badge badge-pill badge-primary p-4 my-1 mx-1">Disponibles :
                <%= happy_price.stock %></span>
              <span class="badge badge-pill badge-primary p-4 my-3">Temps restant :
                <%= happy_price.time_str_french %></span>
              <!-- Happy Minute Begin ) !-->

            <% end %>
            <div class="blog-item-wrapper wow fadeInUp" data-wow-delay="0.3s">
              <div class="blog-item-text">
                <div class="row">
                  <div class="col-4">
                    <% if current_owner == item.business.owner %>
                      <h3>
                        <%= link_to item.title, business_item_path(@business, item) %>
                      </h3>
                    <% else %>
                      <h3>
                        <%= item.title %>
                      </h3>
                    <% end %>
                    <div class="meta-tags">
                      <% item.tags.each do |tag| %>
                        <span class="foodcategory"><i class="lnr lnr-cloud"></i>
                          <%= tag.name %>
                        </span>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-6">
                    <p>
                      <%= item.description %>
                    </p>
                  </div>
                  <div class="col-2">
                    <p>
                      <% if happy_price %>
                        <del>
                          <%= item.price %> € </del>
                      <% else %>
                        <%= item.price %> €
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
              <% if current_owner == item.business.owner && !item.happy_prices.empty? %>
                <ul class="p-2">
                  <% item.happy_prices.each do |happy_price| %>
                    <li>
                      <%= happy_price.price %> € :
                      <% happy_price.happy_codes.each do |happy_code| %>
                        <span class="px-2">
                          <%= "#{happy_code.code}" %> </span>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              <% end %>
              <% if customer_signed_in? && current_customer.happy_codes.any? { |hc| hc.happy_price.item == item } %>
                <p class="p-2"> Mes Happy Codes :
                  <% current_customer.happy_codes.filter { |hc| hc.happy_price.item == item }.each do |happy_code|  %>
                    <span class="px-2">
                      <%= "#{happy_code.code} (#{happy_code.happy_price.price} €)" %> </span>
                  <% end %>
                </p>
              <% end %>
            </div>

            <% if happy_price %>
              <!-- ( Happy Minute End !-->
              <% if current_owner == @business.owner %>
                <%= link_to "Modifier (#{happy_price.price} €)", edit_business_item_happy_price_path(@business, item, happy_price), class: "btn btn-common display-4"%>
              <% elsif customer_signed_in? %>
                <%= link_to "Bénéficier de la promo incroyable !", business_item_happy_price_happy_codes_path(@business, item, happy_price), method: :post, class: "btn btn-primary" %>
              <% else %>
                <%= link_to "Se connecter pour en profiter", new_customer_session_path, class: "btn btn-success" %>
              <% end %>
              <!-- Happy Minute End ) -->
            </div>
          <% end %>
        </div>
        <!-- Item Wrapper ) -->
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/items/_form.html.erb
  <%= form_with(model: [@business, @item], local: true, method: method, class: "col-lg-6") do |form| %>

  <!-- ERRORS !-->
  <% if @item.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <p> Le produit n'a pas pu être créé pour les raisons suivantes :</p>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- title !-->
  <div class="form-group">
    <%= form.label :title, 'Titre' %>
    <%= form.text_field :title, class: "form-control"  %>
  </div>

  <!-- description !-->
  <div class="form-group">
    <%= form.label :description, 'Description' %>
    <%= form.text_area :description, class: "form-control"  %>
  </div>

  <!-- price !-->
  <div class="form-group">
    <%= form.label :price, 'Prix' %>
    <%= form.number_field :price, min: 0.01, step: 0.01, class: "form-control"  %>
  </div>

  <!-- categorie !-->
  <div class="form-group">
    <%= form.label :category_id, ' Catégorie    ' %>
    <%= form.collection_select :category_id, Category.all, :id, :name,  :prompt => 'Sélectionne' %>
  </div>

  <!-- SUBMIT !-->
  <div class="actions mt-5 pr-4">
    <%= form.submit "Valider", class: "btn btn-lg btn-success btn-block" %>
  </div>

  <div class="row justify-content-center">
    <%= link_to "Retour à la carte", business_items_path(@business), class: "btn btn-info" %>
  </div>

<% end %>

app/views/items/_header.html.erb
    <!-- Business Hero Start -->
<div>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="jumbo-business jumbotron jumbotron-fluid py-5">
          <div class="jumbo-business-container container container-fluid py-5">
            <div class="jumbo-title-container col-6">
              <h1 class="jumbo-title pt-3"><%= link_to @business.name, business_path(@business) %></h1>
              <p class="my-3"><%= @business.address %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Business Hero End -->

app/views/items/_item.html.erb
<% happy_price = item.current_happy_price %>
<% happy_price = nil if defined? hide_happy_price %>

<!-- ( Item Wrapper -->
<div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 blog-item">

  <% if happy_price %>
    <!-- ( Happy Minute Begin !-->
    <div class="alert alert-success wow fadeInUp" data-wow-delay="0.3s">
      <p class="display-4"> HAPPY MINUTE : <%= happy_price.price %> € </p>

      <span class="badge badge-pill badge-primary p-4 my-1 mx-1">Disponibles : <%= happy_price.stock %></span>
      <span class="badge badge-pill badge-primary p-4 my-3">Temps restant : <%= happy_price.time_str_french %></span>
      <!-- Happy Minute Begin ) !-->
    <% end %>

    <div class="blog-item-wrapper wow fadeInUp" data-wow-delay="0.3s">
      <div class="blog-item-text">
        <div class="row">
          <div class="col-4">
            <h3>
              <%= item.title %>
            </h3>
            <div class="meta-tags">
              <% item.tags.each do |tag| %>
                <span class="foodcategory"><i class="lnr lnr-cloud"></i>
                  <%= tag.name %>
                </span>
              <% end %>
            </div>
          </div>

          <div class="col-6">
            <p>
              <%= item.description %>
            </p>
          </div>

          <div class="col-2">
            <p>
              <% if happy_price %>
                <del><%= item.price %> € </del>
              <% else %>
                <%= item.price %> €
              <% end %>
            </p>
          </div>
        </div>
      </div>

      <% if current_owner == item.business.owner && !item.happy_prices.filter { |hp| !hp.id.nil? }.empty? %>
        <ul class="p-2">
          <% item.happy_prices.filter { |hp| !hp.id.nil? }.each do |happy_price| %>
            <li> <%= happy_price.price %> € :  
              <% happy_price.happy_codes.each do |happy_code| %>
                <span class="px-2"> <%= "#{happy_code.code}" %> </span>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <% if customer_signed_in? && current_customer.happy_codes.any? { |hc| hc.happy_price.item == item } %>
        <p class="p-2"> Mes Happy Codes : 
          <% current_customer.happy_codes.filter { |hc| hc.happy_price.item == item }.each do |happy_code|  %>
            <span class="px-2">  <%= "#{happy_code.code} (#{happy_code.happy_price.price} €)" %> </span>
          <% end %>
        </p>
      <% end %>

    </div>
    <% if happy_price %>
      <!-- ( Happy Minute End !-->
      <% if current_owner == @business.owner %>
        <%= link_to "Modifier (#{happy_price.price} €)", edit_business_item_happy_price_path(@business, item, happy_price), class: "btn btn-common display-4"%>
      <% elsif customer_signed_in? %>
        <%= link_to "Bénéficier de la promo incroyable !", business_item_happy_price_happy_codes_path(@business, item, happy_price), method: :post, class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Se connecter pour en profiter", new_customer_session_path, class: "btn btn-success" %>
      <% end %>
      <!-- Happy Minute End ) -->
    </div>
  <% end %>
</div>
<!-- Item Wrapper ) -->

app/views/items/edit.html.erb
<%= render partial:"header" %>

<section>
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Modifier un <span>produit</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Merci de modifier les informations du produit </p>
    </div>
    <div class="row justify-content-center">
      <%= render partial: "form", locals: {method: :put} %>
    </div>
  </div>
</section>

<div class="container">
  <div class="section-header">
    <%= link_to "Supprimer", business_item_path(@business, @item), method: :delete, data: {confirm: "Etes-vous sûr ?"}, class: "btn btn-danger" %>
  </div>
</div>

<section id= "blog" class="section">
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Ajouter des <span>Tags</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Précisez la présence d'ingrédients / allergènes (type de produit) </p>
    </div>
    <div class="row justify-content-center mb-5">
      <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
          <% @item.item_tags.filter { |ht| !ht.id.nil? }.each do |item_tag| %>
            <li class="list-group-item d-flex justify-content-around"><%= item_tag.tag.name %>
              <%= link_to business_item_item_tag_path(@business, @item, item_tag), data: {confirm: "Etes-vous sûr ?"}, method: :delete do  %>
                <span class="lnr lnr-trash text-danger"></span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="row justify-content-center">
      <%= form_with(model: [@business, @item, @item_tag], local: true, method: :post, class: "col-lg-6") do |form| %>

        <!-- ERRORS !-->
        <% if @item_tag.errors.any? %>
          <div class="alert alert-warning" role="alert">
            <p> Le tag n'a pas pu être ajouté pour les raisons suivantes :</p>
            <ul>
              <% @item_tag.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <!-- tags !-->
        <div class="form-group">
          <%= form.label :tag_id, ' Nouveau tag ? ' %>
          <%= form.collection_select(:tag_id, Tag.all, :id, :name, :prompt => 'Sélectionne') %>
        </div>

        <!-- SUBMIT !-->
        <div class="actions mt-5 pr-4">
          <%= form.submit "Valider", class: "btn btn-lg btn-success btn-block mb-5" %>
        </div>

      <% end %>

    </div>

  </div>
</section>

app/views/items/index.html.erb
<%= render partial:"header" %>
<section class="section">
  <!-- Container Starts -->
  <div class="container">
    <% if !@business.menus.empty? %>
      <div class="section-header">
        <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Nos <span>Menus</span></h2>
        <hr class="lines wow zoomIn" data-wow-delay="0.3s">
        <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Notre sélection </p>
      </div>
      <div class="col-lg-12 d-flex align-items-center flex-column ">
        <% @business.menus.all.each do |menu| %>
          <div class="card border-success mb-3 text-center" style="width: 30rem;">
            <div class="card-header"><%= link_to menu.name, business_menu_path(@business, menu) %></div>
            <div class="card-body">
              <p><b><%= menu.description %> <%= menu.price %> €</b></p>
              <ul>
                <% menu.items.each do |item| %>
                  <li class="card-title"><%= item.title %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% if @business.owner == current_owner %>
      <div class="row justify-content-center">
        <%= link_to "Ajouter un menu", new_business_menu_path(@business), class: "btn btn-common" %>
      </div>
    <% end %>
  </section>
  <!-- Basic Card Section Section -->
  <section id="blog" class="section">
    <!-- Container Starts -->
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Notre <span>Carte</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Notre sélection </p>
    </div>
    <%= render partial: "category", collection: @categories, as: :category %>
  </div>
</section>
<!-- Basic Card Section End -->
<% if @business.owner == current_owner %>
  <section>
    <!-- Container Starts -->
    <div class="container">
      <div class="section-header">
        <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Espace <span>Gestion</span></h2>
        <hr class="lines wow zoomIn" data-wow-delay="0.3s">
        <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Gérer votre carte </p>
      </div>
      <div class="row justify-content-center">
        <%= link_to "Ajouter un produit", new_business_item_path(@business), class: "btn btn-common" %>
      </div>
    </div>
  </section>
<% end %>

app/views/items/new.html.erb
<%= render partial: "header" %>

<section>
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Ajouter un <span>produit</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Merci de renseigner les informations sur le nouveau produit </p>
    </div>
    <div class="row justify-content-center">
      <%= render partial: "form", locals: {method: :post} %>
    </div>
  </div>
</section>

app/views/items/show.html.erb
<%= render partial: "header" %>

<section id="blog" class="section">
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Plus d'<span>informations</span></h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Caractéristiques du produit </p>
    </div>
    <div class="row justify-content-center">
      <%= render partial: "item", locals:{item: @item} %>
    </div>
    <div class="row justify-content-center">
      <%= link_to "Retour au menu", business_items_path(@business), :class => "btn btn-common my-2 wow zoomIn", data: {"wow-delay"=>"1s"} %>
    </div>
  </div>
</section>
<div class=" col-lg-12 d-flex align-items-center flex-column ">
  <% if @business.owner == current_owner %>
    <ul>
      <%if @item.item_photo.attached?%>
        <%= image_tag @item.item_photo, alt: 'photo' %>
      <%else%>
        <p>=== Il n'y a pas encore de photo pour cette spécialité ===</p>
      <%end%>
      <p class="h4">Changer la photo pour cette spécialité ?</p>
      <%= form_tag business_item_item_photos_path(@business, @item), multipart: true do %>
        <%= file_field_tag :item_photo %>
        <%= submit_tag "mettre à jour", class: "btn btn-outline-secondary btn-sm" %>
      <% end %>
    </ul>
  <% end %>
</div>

<% if @business.owner == current_owner %>
  <section id="blog" class="section">
    <!-- Container Starts -->
    <div class="container">
      <div class="section-header">
        <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s"> Espace <span>Gestion</span></h2>
        <hr class="lines wow zoomIn" data-wow-delay="0.3s">
        <p class="section-subtitle wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"> Gérer votre carte </p>
      </div>

      <% @item.happy_prices.sort_by { |hp| hp.start_date }.each do |upcoming| %>
        <div class="row justify-content-center">
          <div class="col-lg-8 col-md-6 col-sm-6 col-xs-12  alert alert-<%= (upcoming.active? ? ('success') : ('warning')) %>" >
            <%= link_to "Modifier (#{upcoming.price} €)", edit_business_item_happy_price_path(@business, @item, upcoming), class: "btn btn-common display-4"%>
            <p> <%= upcoming.start_date.to_formatted_s(:long) %> ==> <%= upcoming.end_date.to_formatted_s(:long) %> </p>
            <p> <%= upcoming.stock %> unités à <%= upcoming.price %> € (<%= upcoming.active? ? 'EN COURS' : (upcoming.started? ? 'Terminé' : 'A venir') %>)</p>
          </div>
        </div>
      <% end %>

      <div class="row justify-content-center">
        <%= link_to "Modifier le produit", edit_business_item_path(@business, @item), class: "btn btn-common" %>
      </div>
      <div class="row justify-content-center">
        <%= link_to "Mettre en Happy Minute !", new_business_item_happy_price_path(@business, @item), class: "btn btn-common btn-lg" %>
      </div>
      <div class="row justify-content-center">
        <%= link_to "Supprimer le produit", business_item_path(@business, @item), method: :delete, data: {confirm: "Etes-vous sûr ?"}, class: "btn btn-danger" %>
      </div>
    </div>
  </section>
<% end %>